# Site settings
title: Jay Rodge
email: your-email@example.com
description: "Developer Advocate at NVIDIA"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jayrodge.github.io" # the base hostname & protocol for your site
twitter_username: jayrodge
github_username: jayrodge

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page" 